services:
  node1:
    build: .
    restart: unless-stopped
    expose:
      - "8484"
    volumes:
      - limedb_node1_data:/data
    environment:
      - SERVER_PORT=8484
      - NODE_URL=http://node1:8484
      - NODE_PEERS=http://node2:8484

  node2:
    build: .
    restart: unless-stopped
    volumes:
      - limedb_node2_data:/data
    environment:
      - SERVER_PORT=8484
      - NODE_URL=http://node2:8484
      - NODE_PEERS=http://node3:8484

  node3:
    build: .
    restart: unless-stopped
    volumes:
      - limedb_node3_data:/data
    environment:
      - SERVER_PORT=8484
      - NODE_URL=http://node3:8484
      - NODE_PEERS=http://node4:8484

  node4:
    build: .
    restart: unless-stopped
    volumes:
      - limedb_node4_data:/data
    environment:
      - SERVER_PORT=8484
      - NODE_URL=http://node4:8484
      - NODE_PEERS=http://node1:8484

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - LIMEDB_SEED_URL=http://node1:8484
    depends_on:
      - node1
    networks:
      - default
      - caddy
    labels:
      caddy: http://limedb.namanvashistha.com
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  caddy:
    external: true

volumes:
  limedb_node1_data:
  limedb_node2_data:
  limedb_node3_data:
  limedb_node4_data:
